using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class AvatarSyncModel {
    [RealtimeProperty(1, true, true)]
    private string _avatar;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class AvatarSyncModel : IModel {
    // Properties
    public string avatar {
        get { return _cache.LookForValueInCache(_avatar, entry => entry.avatarSet, entry => entry.avatar); }
        set { if (value == avatar) return; _cache.UpdateLocalCache(entry => { entry.avatarSet = true; entry.avatar = value; return entry; }); FireAvatarDidChange(value); }
    }
    
    // Events
    public delegate void AvatarDidChange(AvatarSyncModel model, string value);
    public event         AvatarDidChange avatarDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool   avatarSet;
        public string avatar;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public AvatarSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireAvatarDidChange(string value) {
        try {
            if (avatarDidChange != null)
                avatarDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Avatar = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _avatar = avatar;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteStringLength((uint)PropertyID.Avatar, _avatar);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.avatarSet)
                    length += WriteStream.WriteStringLength((uint)PropertyID.Avatar, entry.avatar);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteString((uint)PropertyID.Avatar, _avatar);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.avatarSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.avatarSet)
                    stream.WriteString((uint)PropertyID.Avatar, entry.avatar);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool avatarExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.avatarSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Avatar: {
                    string previousValue = _avatar;
                    
                    _avatar = stream.ReadString();
                    
                    if (!avatarExistsInChangeCache && _avatar != previousValue)
                        FireAvatarDidChange(_avatar);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
