using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PodiumSyncModel
{
    [RealtimeProperty(1, true, true)]
    private int _podium;
}
/* ----- Begin Normal Autogenerated Code ----- */
public partial class PodiumSyncModel : IModel {
    // Properties
    public int podium {
        get { return _cache.LookForValueInCache(_podium, entry => entry.podiumSet, entry => entry.podium); }
        set { if (value == podium) return; _cache.UpdateLocalCache(entry => { entry.podiumSet = true; entry.podium = value; return entry; }); FirePodiumDidChange(value); }
    }
    
    // Events
    public delegate void PodiumDidChange(PodiumSyncModel model, int value);
    public event         PodiumDidChange podiumDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool podiumSet;
        public int  podium;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public PodiumSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FirePodiumDidChange(int value) {
        try {
            if (podiumDidChange != null)
                podiumDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Podium = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _podium = podium;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Podium, (uint)_podium);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.podiumSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.Podium, (uint)entry.podium);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.Podium, (uint)_podium);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.podiumSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.podiumSet)
                    stream.WriteVarint32((uint)PropertyID.Podium, (uint)entry.podium);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool podiumExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.podiumSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Podium: {
                    int previousValue = _podium;
                    
                    _podium = (int)stream.ReadVarint32();
                    
                    if (!podiumExistsInChangeCache && _podium != previousValue)
                        FirePodiumDidChange(_podium);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */