using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class EventSyncModel
{
    [RealtimeProperty(1, true, true)]
    private string _events;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class EventSyncModel : IModel {
    // Properties
    public string events {
        get { return _cache.LookForValueInCache(_events, entry => entry.eventsSet, entry => entry.events); }
        set { if (value == events) return; _cache.UpdateLocalCache(entry => { entry.eventsSet = true; entry.events = value; return entry; }); FireEventsDidChange(value); }
    }
    
    // Events
    public delegate void EventsDidChange(EventSyncModel model, string value);
    public event         EventsDidChange eventsDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool   eventsSet;
        public string events;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public EventSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireEventsDidChange(string value) {
        try {
            if (eventsDidChange != null)
                eventsDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Events = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _events = events;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteStringLength((uint)PropertyID.Events, _events);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.eventsSet)
                    length += WriteStream.WriteStringLength((uint)PropertyID.Events, entry.events);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteString((uint)PropertyID.Events, _events);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.eventsSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.eventsSet)
                    stream.WriteString((uint)PropertyID.Events, entry.events);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool eventsExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.eventsSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Events: {
                    string previousValue = _events;
                    
                    _events = stream.ReadString();
                    
                    if (!eventsExistsInChangeCache && _events != previousValue)
                        FireEventsDidChange(_events);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
