using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RecipeSyncModel {
    [RealtimeProperty(1, true, true)]
    private string _avatarRecipe;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RecipeSyncModel : IModel {
    // Properties
    public string avatarRecipe {
        get { return _cache.LookForValueInCache(_avatarRecipe, entry => entry.avatarRecipeSet, entry => entry.avatarRecipe); }
        set { if (value == avatarRecipe) return; _cache.UpdateLocalCache(entry => { entry.avatarRecipeSet = true; entry.avatarRecipe = value; return entry; }); FireAvatarRecipeDidChange(value); }
    }
    
    // Events
    public delegate void AvatarRecipeDidChange(RecipeSyncModel model, string value);
    public event         AvatarRecipeDidChange avatarRecipeDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool   avatarRecipeSet;
        public string avatarRecipe;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public RecipeSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireAvatarRecipeDidChange(string value) {
        try {
            if (avatarRecipeDidChange != null)
                avatarRecipeDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        AvatarRecipe = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _avatarRecipe = avatarRecipe;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteStringLength((uint)PropertyID.AvatarRecipe, _avatarRecipe);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.avatarRecipeSet)
                    length += WriteStream.WriteStringLength((uint)PropertyID.AvatarRecipe, entry.avatarRecipe);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteString((uint)PropertyID.AvatarRecipe, _avatarRecipe);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.avatarRecipeSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.avatarRecipeSet)
                    stream.WriteString((uint)PropertyID.AvatarRecipe, entry.avatarRecipe);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool avatarRecipeExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.avatarRecipeSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.AvatarRecipe: {
                    string previousValue = _avatarRecipe;
                    
                    _avatarRecipe = stream.ReadString();
                    
                    if (!avatarRecipeExistsInChangeCache && _avatarRecipe != previousValue)
                        FireAvatarRecipeDidChange(_avatarRecipe);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
